changed web app health check endpoint and changed docker build-image workflow to including api test

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -1,45 +1,70 @@
 name: Publish Docker Image
 
 on:
-  release:
-    types: [ "published" ]
+  pull_request:
+    branches:
+      - develop
 
 env:
   REGISTRY: ${{ vars.REGISTRY }}
   IMAGE_NAME: ${{ vars.IMAGE_NAME }}
+  IMAGE_TAG: pr-${{ github.event.pull_request.number }}
 
 jobs:
-  push_to_registry:
-    name: Push Docker Image to Docker Hub
+  build_test_push:
     runs-on: ubuntu-latest
-    permissions:
-      packages: write
-      contents: read
-      attestations: write
-      id-token: write
-      
+
     steps:
-      - name: Checkout repository 
+      - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Log in to DockerHub
+      - name: Log in to Docker Hub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: Extract metadata (tags, labels) for Docker
+      - name: Extract Docker metadata
         id: meta
         uses: docker/metadata-action@v5
         with:
-          images: ${{env.REGISTRY }}/${{ env.IMAGE_NAME }}
-          tags: ${{ github.ref_name }}  # Use the release tag (e.g., v1.0.0) as the image tag
+          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
+          tags: ${{ env.IMAGE_TAG }} # Use the PR number as the image tag
 
-      - name: Build and push Docker Image
-        id: push
+      - name: Build Docker image (but don't push yet)
         uses: docker/build-push-action@v5
         with:
           context: .
+          load: true #Load locally instead of pushing
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
+
+      - name: Run FastAPI contiainer and test API endpoint
+        run: |
+          docker run -d --name api_test_container -p 80:80 ${{steps.meta.outputs.tags}}
+
+          echo "Waiting for API to start..."
+          sleep 5
+
+          echo "Hitting the API endpoint..."
+          curl --fail http://localhost:80/health
+
+          if [ $? -ne 0 ]; then
+            echo "API health check failed!"
+            exit 1
+          else
+            echo "API is healthy!"
+          fi
+
+      - name: Stop and remove test container
+        if: always() # Ensure cleanup happens even if tests fail
+        run: docker rm -f api_test_container || true
+
+      - name: Push Docker image (only if tests passed)
+        if: success() # Only push if previous steps succeeded
+        uses: docker/build-push-action@v5
+        with:
+          context: .
           push: true
+          tags: ${{ steps.meta.outputs.tags }}
+          labels: ${{ steps.meta.outputs.labels }}
